######################################################################
#                             -- test --                              #
######################################################################
######################################################################
#                          -- spring --                              #
######################################################################
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ll?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password:
    hikari:
      schema: classpath:sql

  ############################ --  servlet -- ############################
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB

  ############################ --  devtools -- ############################
  devtools:
    restart:
      # 热部署开关
      enabled: true

######################################################################
#                            -- log --                               #
######################################################################
logging:
  level:
    com.ll: debug
    org.springframework: warn